[package]
org = "ballerina"
name = "mime"
version = "2.5.0"
authors = ["Ballerina"]
keywords = ["mime", "multipart", "entity"]
repository = "https://github.com/ballerina-platform/module-ballerina-mime"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.3.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mime-native"
version = "2.5.0"
path = "../native/build/libs/mime-native-2.5.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/mime-test-utils-2.5.0-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/mimepull-1.9.11.jar"
groupId = "org.jvnet.mimepull"
artifactId = "mimepull"
version = "1.9.11"

[[platform.java11.dependency]]
path = "./lib/jakarta.activation-1.2.2.jar"
groupId = "com.sun.activation"
artifactId = "jakarta.activation"
version = "1.2.2"
