[package]
org = "ballerina"
name = "mime"
version = "2.11.0"
authors = ["Ballerina"]
keywords = ["mime", "multipart", "entity"]
repository = "https://github.com/ballerina-platform/module-ballerina-mime"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "mime-native"
version = "2.11.0"
path = "../native/build/libs/mime-native-2.11.0.jar"

[[platform.java21.dependency]]
path = "../test-utils/build/libs/mime-test-utils-2.11.0.jar"
scope = "testOnly"

[[platform.java21.dependency]]
path = "./lib/mimepull-1.9.11.jar"
groupId = "org.jvnet.mimepull"
artifactId = "mimepull"
version = "1.9.11"

[[platform.java21.dependency]]
path = "./lib/jakarta.activation-api-2.0.1.jar"
groupId = "jakarta.activation"
artifactId = "jakarta.activation-api"
version = "2.0.1"
